[package]
name = "amdgpu_top_gui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libamdgpu_top = { path = "../libamdgpu_top" }
eframe = { version = "^0.22.0", default-features = false, features = [ "default_fonts", "glow", "wayland" ] }
